<a href="https://colab.research.google.com/github/HarishSivakumaran/ML-Projects/blob/main/ml_algos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

💻 Day 1 Hands-On Practice ExercisesArray Mutation Challenge: Write a function that takes a 1D array of length $N$ and replaces all negative values with $0.0$ using .at[].set() and jnp.where.PRNG Pipeline: Build a key-splitting loop that generates $5$ distinct mini-batches of Gaussian noise without ever reusing a key.PyTree Optimizer: Define a nested dictionary with weights, biases, and hyperparameters. Write a custom jax.tree.map call that computes the L2 norm ($\sum w^2$) of all weight arrays while ignoring scalar learning rates.

In [3]:
import jax
import jax.numpy as jnp

def relu(arr: jnp.ndarray):
  return jnp.where(arr >= 0, arr, 0.0)

test = jnp.array([-1.0, 0, 1.0, 2, 3])

print(relu(test))
in_place = test.at[jnp.where(test < 0)].set(0.0)
print(jnp.where(test < 0))
print(in_place)
print(test)

[0. 0. 1. 2. 3.]
(Array([0], dtype=int32),)
[0. 0. 1. 2. 3.]
[-1.  0.  1.  2.  3.]
