<a href="https://colab.research.google.com/github/HarishSivakumaran/ML-Projects/blob/main/ml_algos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

💻 Day 2 Hands-On Practice ExercisesTracing vs. Runtime Print Challenge: Write a @jax.jit function that computes $y = x^2 + 1$. Add both a standard print(x) statement and a jax.debug.print("Runtime x: {}", x) statement. Run it twice with different inputs and explain what is output on each call910.Fixing Control Flow: Take the following function that throws an error when wrapped in @jax.jit, and fix it using static_argnames:def scale_mode(x, mode="double"):
    if mode == "double":
        return x * 2.0
    else:
        return x * 0.5

In [5]:
import jax
import jax.numpy as jnp

def apply(x):
  print(x)
  jax.debug.print("Runtime x: {}", x)
  return jnp.square(x) + 1

print(apply(jnp.array([2.0, 3.0, 4.0])))
print(apply(5.0))
print(apply(9))

jit_apply = jax.jit(apply)

print(jit_apply(jnp.array([2.0, 3.0, 4.0])))
print(jit_apply(jnp.array([3.0, 4.0, 5.0])))
print(jit_apply(5.0))
print(jit_apply(6.0))
print(jit_apply(9))
print(jit_apply(17))


[2. 3. 4.]
Runtime x: [2. 3. 4.]
[ 5. 10. 17.]
5.0
Runtime x: 5.0
26.0
9
Runtime x: 9
82
JitTracer(float32[3])
Runtime x: [2. 3. 4.]
[ 5. 10. 17.]
Runtime x: [3. 4. 5.]
[10. 17. 26.]
JitTracer(~float32[])
Runtime x: 5.0
26.0
Runtime x: 6.0
37.0
JitTracer(~int32[])
Runtime x: 9
82
Runtime x: 17
290


💻 Day 1 Hands-On Practice ExercisesArray Mutation Challenge: Write a function that takes a 1D array of length $N$ and replaces all negative values with $0.0$ using .at[].set() and jnp.where.PRNG Pipeline: Build a key-splitting loop that generates $5$ distinct mini-batches of Gaussian noise without ever reusing a key.PyTree Optimizer: Define a nested dictionary with weights, biases, and hyperparameters. Write a custom jax.tree.map call that computes the L2 norm ($\sum w^2$) of all weight arrays while ignoring scalar learning rates.

In [ ]:
import jax
import jax.numpy as jnp

def relu(arr: jnp.array):
  return jnp.where(arr >= 0, arr, 0.0)

test = jnp.array([-1.0, 0, 1.0, 2, 3])

print(relu(test))
in_place = test.at[jnp.where(test < 0)].set(0.0)
print(jnp.where(test >= 0))
print(in_place)
print(test)

[0. 0. 1. 2. 3.]
(Array([1, 2, 3, 4], dtype=int32),)
[0. 0. 1. 2. 3.]
[-1.  0.  1.  2.  3.]


In [ ]:
import jax
import jax.numpy as jnp


def gaussian_sample(key, shape):
  return jax.random.normal(key, shape)

root_key = jax.random.key(42)

for i in range(5):
  k1, k2 = jax.random.split(root_key, 2)
  print(gaussian_sample(k1, (10, )))
  root_key = k2

[ 0.07592554 -0.48634264  1.2903206   0.5196119   0.30040437  0.31034866
  0.5761609  -0.8074621  -1.9883217   0.6395295 ]
[-0.74412036  1.52171     0.1847949  -1.1812532  -0.67319936 -0.32261458
  0.05882881  1.5566975   2.0083923   0.97201616]
[-0.92217225  1.2502675  -1.4594661  -0.6433759   0.10886536  0.5296943
 -1.7170644   0.30685094  0.5052932  -0.4425835 ]
[-0.8789221   1.7597361  -1.7431877   0.28519595  0.13290869 -2.3614807
  0.99604434 -0.21629068  3.365236   -0.03634243]
[-0.24331857 -0.05206627 -0.5459883   0.5970541   0.3256138  -0.21120721
 -0.5110182   1.2065462  -1.715144   -0.6556372 ]


In [ ]:
import jax
import jax.numpy as jnp

params = {
    "weights": jnp.array([[1,2,3], [4,5,6]]),
    "biases": jnp.array([0.1, 0.2, 0.3]),
    "learning_rate": 0.01
}

def calc_l2(params):
  def leaf_with_path(path, leaf):
    keys = [p.key for p in path]
    if 'weights' in keys and isinstance(leaf, jax.Array):
      return jnp.sum(jnp.square(leaf))
    else:
      return jnp.array(0.0)
  return jax.tree_util.tree_map_with_path(leaf_with_path, params)

print(calc_l2(params))



{'biases': Array(0., dtype=float32, weak_type=True), 'learning_rate': Array(0., dtype=float32, weak_type=True), 'weights': Array(91, dtype=int32)}
